#!/bin/bash
#BSUB -J europe_osm_4
#BSUB -e europe_osm_4.%J.err
#BSUB -o europe_osm_4.%J.out
#BSUB -nnodes 4
#BSUB -W 00:15
#BSUB -P CSC422
#BSUB -alloc_flags "gpumps gpudefault smt1"

module load gcc
module load cmake/3.18.1
module load cuda

cd /ccs/home/bienz/sparse_mat

echo "jsrun -a36 -c36 -g6 -r1 -n4 -M "-gpu" --latency_priority=gpu-cpu --launch_distribution=packed ./mpi_sparse_mat suitesparse/europe_osm.pm"


jsrun -a36 -c36 -g6 -r1 -n4 -M "-gpu" --latency_priority=gpu-cpu --launch_distribution=packed  ./mpi_sparse_mat suitesparse/europe_osm.pm




